dbpedia/extraction-framework

core/src/main/scala/org/dbpedia/extraction/config/transform/TemplateTransformConfig.scala
core/src/main/scala/org/dbpedia/extraction/destinations/formatters/UriPolicy.scala
core/src/main/scala/org/dbpedia/extraction/destinations/formatters/UriTripleBuilder.scala
core/src/main/scala/org/dbpedia/extraction/mappings/ConstantMapping.scala
core/src/main/scala/org/dbpedia/extraction/mappings/HomepageExtractor.scala
core/src/main/scala/org/dbpedia/extraction/mappings/PageContext.scala
core/src/main/scala/org/dbpedia/extraction/util/UriUtils.scala
core/src/main/scala/org/dbpedia/extraction/wikiparser/NodeUtil.scala
core/src/main/scala/org/dbpedia/extraction/wikiparser/impl/simple/SimpleWikiParser.scala
core/src/main/scala/org/dbpedia/extraction/wikiparser/impl/sweble/SwebleWrapper.scala
core/src/test/scala/org/dbpedia/extraction/destinations/formatters/UriPolicyTest.scala
dump/extraction.default.properties
live/pom.xml
pom.xml
wiktionary/src/main/scala/org/dbpedia/extraction/mappings/WiktionaryPageExtractor.scala
wiktionary/src/main/scala/org/dbpedia/extraction/mappings/wikitemplate/NodeHandler.scala
wiktionary/src/main/scala/org/dbpedia/extraction/mappings/wikitemplate/WiktionaryUtils.scala

IDN support and improvement of external link handling
Testing this in Dutch it increased the extracted triples and decreased the "BAD URI" triples

IDN support and improvement of external link handling

---

core/src/main/scala/org/dbpedia/extraction/config/dataparser/ParserUtilsConfig.scala
core/src/test/scala/org/dbpedia/extraction/dataparser/DoubleParserTest.scala

BG place coordinates fix

---

server/src/main/statistics/ignorelist_en.txt

Related to https://github.com/dbpedia/mappings-tracker/issues/19 and https://github.com/dbpedia/extraction-framework/issues/335

removed template Listen and added 27 of its props

---

server/src/main/statistics/ignorelist_nl.txt

stale interlanguage links (non Wikidata)

ignore Bronvermelding_anderstalige_Wikipedia

---

server/src/main/statistics/ignorelist_en.txt

https://github.com/dbpedia/mappings-tracker/issues/40

Remove Infobox_venue, Infobox_dam, Authority_control

---

live/pom.xml
live/src/main/java/org/dbpedia/extraction/live/storage/JSONCache.scala

Removed scala.util.parsing.json dependencies and replaced the json parsing with jackson-module-scala

Issue #277: remove scala.util.parsing.json dependencies (deprecated)

---

core/src/main/scala/org/dbpedia/extraction/mappings/IntermediateNodeMapping.scala

see #364 
if nobody opposes the change...

enable empty properties on IntermediateNodeMapping

---

scripts/pom.xml
scripts/src/main/scala/org/dbpedia/extraction/scripts/TypeConsistencyCheck.scala

Type checking post processing script that validates the facts from the MappingExtractor

Type checking post processing script

---

core/src/main/scala/org/dbpedia/extraction/mappings/wikidata/WikidataLLExtractor.scala
core/src/main/scala/org/dbpedia/extraction/mappings/wikidata/WikidataSameAsExtractor.scala

Solution for https://github.com/dbpedia/extraction-framework/issues/405

Fixed character decoding issue. Now decodes only one time.

---

live/pom.xml

Fix error introduced in PR #358

Updated jackson module

---

core/src/main/java/org/dbpedia/extraction/sources/WikipediaDumpParser.java

Fix NoSuchElementException

---

.travis.yml
core/pom.xml
dump/pom.xml
live/pom.xml
pom.xml
scripts/pom.xml
server/pom.xml
wiktionary/pom.xml

- Added required info and in poms (for master);
Could you, please, might check the new info added in pom(mainly licenses and description) ?
Tasks

Maven central deployment

---

dump/download.10000.properties
dump/download.minimal.properties
dump/download.wikidata.properties

Fix #448 to use https for download

---

server/src/main/scala/org/dbpedia/extraction/server/resources/TemplateStatistics.scala

Fixed typo

---

core/src/main/scala/org/dbpedia/extraction/dataparser/UnitValueParser.scala
core/src/main/scala/org/dbpedia/extraction/ontology/OntologyDatatypes.scala
core/src/test/scala/org/dbpedia/extraction/dataparser/UnitValueParserTest.scala

Includes support for aliases of meter, foot and inch.
this commit fixes #476

Support for parsing height aliases

---

scripts/src/main/scala/org/dbpedia/extraction/scripts/UnmodifiedFeederCacheGenerator.scala

This PR adds the pageTitle to the SQL file which is generated by the UnmodifiedFeederCacheGenerator. With this PR, we tackle the [issue commented on our PR #470](https://github.com/dbpedia/extraction-framework/pull/470#discussion_r75441863). As far as I was able to find out, this is the last SQL statement which didn't used the pageTitle.
In addition, I removed the `now()` string from the comment below. As the timestamp argument will be passed to the SQL statement directly and put in a bracket of single quotes, this isn't recognized as the current timestamp function but as an invalid timestamp. (It must be `now()` instead of `'now()'`).

Add pageTitle to UnmodifiedFeederCacheGenerator

---

live/live.default.ini
live/live_commons.default.ini
live/src/main/java/org/dbpedia/extraction/live/feeder/RCStreamFeeder.java

This PR adds support for automatic RCStream reconnect attempts in case of an SocketIOException.

Add automatic reconnect option for RCStream

---

core/src/main/resources/wikidatar2r.json

New mappings were added using P1630 -> "rdfs:seeAlso". 
New number of mappings: 1870
Total number of mappings: 2141

New mappings were added

---

core/pom.xml
core/src/main/resources/universal.properties
core/src/main/scala/org/dbpedia/extraction/mappings/ExtractionMonitor.scala

Fixed:
ExtractionMonitor: DataID comparison
Universal.properties: naming adjustments

ExtractionMonitor Fix

---

core/src/main/scala/org/dbpedia/extraction/dataparser/ParserUtils.scala

Adding grouping seperators in large Numbers (eg million, billion) to fix a bug.

fix for ParserUtils-Bug

---

core/pom.xml
dump/extraction.spark.properties
dump/pom.xml

As Requested, I updated the dependencies of the project modules to fix several security alerts

Dependency update

---

QuickStart.md

QuickStart.md: Fixing typo

---

core/src/main/scala/org/dbpedia/extraction/mappings/wikidata/WikidataLexemeExtractor.scala
core/src/main/scala/org/dbpedia/extraction/util/WikidataUtil.scala
dump/src/test/resources/wikidata.extraction.properties

Lexeme extractor extracts data on the form of
```
<http://lex.dbpedia.org/resource/cèdre> <http://www.w3.org/2002/07/owl#sameAs> <http://www.wikidata.org/entity/L222070> .
<http://lex.dbpedia.org/resource/cèdre> <http://www.w3.org/2002/07/owl#sameAs> <http://www.wikidata.org/entity/L222070-F1> .
<http://lex.dbpedia.org/resource/cèdres> <http://www.w3.org/2002/07/owl#sameAs> <http://www.wikidata.org/entity/L222070-F2> .
```

Implemented Lexeme Extractor

---

core/src/main/scala/org/dbpedia/extraction/mappings/wikidata/WikidataLexemeExtractor.scala
core/src/main/scala/org/dbpedia/extraction/util/WikidataUtil.scala

fixed getWikiCommons method in WikidataUtil

fixed getWikiCommons method in WikidataUtil

---

core/src/main/scala/org/dbpedia/extraction/mappings/CitationExtractor.scala

Implemented citation source type matching and added some templates regexes for different languages

Citation Extractor changes

---

core/src/main/scala/org/dbpedia/extraction/mappings/InfoboxReferencesExtractor.scala

Corrected version of InfoboxReferencesExtractor based on PageNodeExtractor

InfoboxReferencesExtractor - corrections

---

core/src/main/scala/org/dbpedia/extraction/ontology/io/OntologyOWLWriter.scala

Adds dct:license

---

core/src/main/java/org/dbpedia/extraction/nif/LinkExtractor.java
core/src/main/scala/org/dbpedia/extraction/config/Config.scala
core/src/main/scala/org/dbpedia/extraction/mappings/NifExtractor.scala
core/src/main/scala/org/dbpedia/extraction/mappings/PlainAbstractExtractor.scala
core/src/main/scala/org/dbpedia/extraction/nif/HtmlNifExtractor.scala
core/src/main/scala/org/dbpedia/extraction/nif/WikipediaNifExtractor.scala
core/src/main/scala/org/dbpedia/extraction/nif/WikipediaNifExtractorRest.scala
core/src/main/scala/org/dbpedia/extraction/util/MediaWikiConnector.scala
core/src/main/scala/org/dbpedia/extraction/util/MediaWikiConnectorAbstract.scala
core/src/main/scala/org/dbpedia/extraction/util/MediaWikiConnectorRest.scala
core/src/main/scala/org/dbpedia/extraction/util/MediawikiConnectorConfigured.scala
dump/src/test/bash/createMinidump_custom_sample.sh
dump/src/test/bash/createSampleRandomFromPageIDdataset.sh
dump/src/test/bash/create_custom_sample.sh
dump/src/test/resources/extraction-configs/extraction.nif.abstracts.properties
dump/src/test/resources/extraction-configs/extraction.plain.abstracts.properties
dump/src/test/scala/org/dbpedia/extraction/dump/ExtractionTestAbstract.md
dump/src/test/scala/org/dbpedia/extraction/dump/ExtractionTestAbstract.scala

Pushing all the work made during the GSOC

GSOC final pull request
